name: Lint and Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black isort mypy types-PyYAML

      - name: Run Ruff (linter)
        run: ruff check src

      - name: Run Black (check formatting)
        run: black --check src

      - name: Run isort (check import sorting)
        run: isort --check-only src

      - name: Run mypy (type checking)
        run: mypy src
